export const productdetails = [
  {
    id: 1,
    img: "https://www.electronicscomp.com/image/cache/catalog/raspberry-pi-3-b-plus-india-200x200.jpg",
    name: "Raspberry Pi 3 - Model B+ - 1.4Ghz 64Ghz Processor with 1 GB Ram (Original)",
    price: 3049.0,
    qty: 0,
  },
  {
    id: 2,
    img: "https://www.electronicscomp.com/image/cache/catalog/uno-r3-smd-compatible-model-200x200.png",
    name: "UNO R3 SMD Atmega328P Board - Clone Compatible Model",
    price: 213.0,
    qty: 0,
  },
  {
    id: 3,
    img: "https://www.electronicscomp.com/image/cache/catalog/soldron-25w-soldering-iron-200x200.jpg",
    name: "Soldron 25W/230V High Quality Soldering Iron",
    price: 310.0,
    qty: 0,
  },
  {
    id: 4,
    img: "https://www.electronicscomp.com/image/cache/catalog/atmega328p-microcontroller-india-200x200.jpg",
    name: "ATmega328P Microcontroller",
    price: 245.0,
    qty: 0,
  },
  {
    id: 5,
    img: "https://techiesms.com/wp-content/uploads/2024/10/nrf-sense-1.png",
    name: "Seeed Studio XIAO nRF52840",
    price: 1483.05,
    qty: 0,
  },
  {
    id: 6,
    img: "https://techiesms.com/wp-content/uploads/2022/11/ESP32-300x300-copy.png",
    name: "Esp:32",
    price: "320",
    qty: 0,
  },
  {
    id: 7,
    img: "https://techiesms.com/wp-content/uploads/2023/01/Image1-768x768.png",
    name: "TTl programmer",
    price: 295.76,
    qty: 0,
  },
  {
    id: 8,
    img: "https://techiesms.com/wp-content/uploads/2024/10/D1MINI.png",
    name: "1 Mini V2 NodeMCU ",
    price: 148.31,
    qty: 0,
  },
  {
    id: 9,
    img: "https://techiesms.com/wp-content/uploads/2023/06/ESP12E-1.png",
    name: "ESP-12E",
    price: 105.93,
    qty: 0,
  },
  {
    id: 10,
    img: "https://techiesms.com/wp-content/uploads/2022/11/keypad.png",
    name: "Matrix Membrane",
    price: 46.61,
    qty: 0,
  },
];
export default function Reducer(state = productdetails, action) {}
